### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Fonta1n3**
Please check out my wallets: BitSense (iOS mobile) and Fully Noded (iOS mobile). 

https://itunes.apple.com/id/app/bitsense-bitcoin-wallet/id1318064671?mt=8

https://itunes.apple.com/us/app/fully-noded/id1436425586?mt=8

BitSense is a mobile wallet that relies on APIs for creating/sending the transactions and utilizes CoreBitcoin to do everything else locally on the iPhone.

Fully Noded is for anyone who is running a node to connect to, to send/receive Bitcoin using Bech32 and RBF.

Thanks and keep up the amazing work!

### CODE REVIEW

**Comment by nopara73** [comment]
Since I don't have iOS/iPad, I'll have many questions, because I won't be able to test myself, so please try to answer honestly. First, let me try to digest it and let me know if I'm mistaken:   

So, there's the wallet, called "Fully Noded", which connects to your own full node and helps you control it over iOS/iPad.  
And there is another iOS/iPad wallet, which is called BitSense.  

First, do you have technical documentation on the architecture for these wallets? So I can dig into them and spare you from asking many small questions.  
Also do you have source code for BitSense? I've found it for Fully Noded (https://github.com/FontaineDenton/Fully_Noded).

**Comment by Fonta1n3** [comment]
Hello,

You are correct.

No i have not written technical documentation on them yet. But i can do to help explain how they work. I am not a professional developer so please bare with me..

Here is the source code for BitSense which was originally called BitKey:

https://github.com/FontaineDenton/BitKey/tree/master/BitKeys

Happy to answer any questions :)

Best Regards,

Peter Denton
3.4u Inspection Engineer
+62(0)81236623884

**Comment by nopara73** [comment]
Let's start with the privacy section. The only thing that is not clear there is the way the wallets fetching blockchain data.    

- Fully Noded uses the users' own Core node. Right?
- Is there any other way/settings that Fully Noded can be configured to?
- What about BitSense? Is it using CoreBitcoin's SPV mode or is it directly connecting to a backend server?
- Is there any other way/settings that BitSense can be configured to?

**Comment by Fonta1n3** [comment]
Hello,

Thank you for your time!

> Fully Noded uses the users' own Core node. Right?
Correct, it is the pure way to use Bitcoin. 100% your node does everything.
> Is there any other way/settings that Fully Noded can be configured to?
No, the only settings are to set the mining fee, or delete the log in credentials to connect to your node. The settings for the node can only be changed via the config file of the node itself.
> What about BitSense? Is it using CoreBitcoin's SPV mode or is it directly connecting to a backend server?

BitSense is using various APIs to fetch blockchain data.
> Is there any other way/settings that BitSense can be configured to?

BitSense is useful/different bc you can put it in cold mode or hot mode. The signing of the transaction happens 100% locally on the device so private keys are only stored locally (or not at all in cold mode) and fully encrypted. You can even turn your Wifi off to scan a private key to sign a transaction.

BitSense is like a tool kit that is focused on offline usage (creating mnemonics, uploading recovery phrases, creating watch only HD wallet by importing XPUB, sweeping private keys, fiat conversions, add labels to addresses etc).

I will attach a pics of the settings for BitSense so you can see what the settings options are :)







Best Regards,

Peter Denton
3.4u Inspection Engineer
+62(0)81236623884

**Comment by nopara73** [comment]
Thanks for answering, I created the lines, if something is not clear, please ask me.  
I have only one question left, which I couldn't decide on, so it's possible incorrect data got into a row.  
In Fully Noded, where are the private keys? Are they in Bitcoin Core or in Fully Noded wallet? Or in other words, are you using the RPC wallet functionality or not?

**Comment by Fonta1n3** [comment]
In Fully Noded the private keys never leave Bitcoin Core, the app only uses the built in API for bitcoin core, it just makes curl commands to the node via RPC and nothing else. 

Best Regards,

Peter Denton
3.4u Inspection Engineer
+62(0)81236623884

**Comment by nopara73** [comment]
I see. Then another tick goes for Fully Noded. Thanks a lot for the replies!

**Pull request closed without merging**
